version: '2'

services:
  postgres:
    build:
      dockerfile: Dockerfile-${DOCKERFILE_FLAVOUR}
      context: 'postgres'
      args:
        - POSTGRES_BASE_IMAGE_VERSION=${POSTGRES_BASE_IMAGE_VERSION}
    image: ${POSTGRES_IMAGE_NAME}:${POSTGRES_BASE_IMAGE_VERSION}${POSTGRES_IMAGE_VERSION_SUFFIX}
    volumes:
      - ./_db-volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - dbnet
