version: '2'

services:
  postgres:
    build:
      dockerfile: Dockerfile-${DOCKERFILE_FLAVOUR}
      context: 'postgres'
      args:
        - POSTGRES_BASE_IMAGE_VERSION=${POSTGRES_BASE_IMAGE_VERSION}
    image: ${POSTGRES_IMAGE_NAME}:${POSTGRES_BASE_IMAGE_VERSION}${POSTGRES_IMAGE_VERSION_SUFFIX}
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    networks:
      - dbnet

  php:
    networks:
      - dbnet

networks:
  dbnet:
    external: false

volumes:
  pgdata:
    external: true
