# NGINX Docker image for Mailery runtime
# ==============================================

ARG NGINX_BASE_IMAGE_VERSION
FROM nginx:${NGINX_BASE_IMAGE_VERSION}

# Add configuration files
COPY image-files/ /
