# Redis Docker image for Mailery runtime
# ==============================================

ARG BEANSTALKD_CONSOLE_BASE_IMAGE_VERSION
FROM schickling/beanstalkd-console:${BEANSTALKD_CONSOLE_BASE_IMAGE_VERSION}
